sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker
deploy:
  - provider: script
    script: bash ./deploy.sh
    # after_deploy: docker build -t arcblock/abtnode:latest --no-cache .
    on:
      branch: master