sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker
deploy:
  - provider: script
    script: docker --version
    after_script: docker build -t arcblock/abtnode:latest --no-cache .
    on:
      branch: master