sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker
deploy:
  - provider: script
    script: docker build -t arcblock/abtnode:latest --no-cache .
    after_success: 'docker image ls'
    on:
      branch: master