sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker

deploy:
  - provider: script
    script: docker build -t arcblock/abtnode:latest --no-cache .
    on:
      branch: master

after_deploy:
  - provider: script
    script: docker image ls
    on:
      branch: master