sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker
deploy:
  - provider: script
    script: docker --version
    # after_deploy: docker build -t arcblock/abtnode:latest --no-cache .
    after_deploy: echo "--------------"
    on:
      branch: master